export const PET_CSS = `
[data-web-pet-root]{--pet-accent:#F58220;--pet-dark:#7A2E00;position:fixed;right:24px;bottom:20px;z-index:2147483000;font-family:Inter,"PingFang SC",system-ui,sans-serif;color:#fff8ec;user-select:none}
.webpet-panel{position:relative;width:280px;height:360px;filter:drop-shadow(0 18px 36px #4a1b0044);touch-action:none;transition:opacity .2s,scale .2s}
.webpet-panel button{border:1px solid #ffd1a766;color:#fff;background:#6f2b0bd9;box-shadow:0 5px 14px #4a1b0040;backdrop-filter:blur(9px);cursor:pointer;transition:transform .15s,background .15s,opacity .15s}.webpet-panel button:hover{background:var(--pet-accent);transform:translateY(-2px)}
.webpet-close{font-size:15px;opacity:.72}.webpet-close:hover{opacity:1}
.webpet-status{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.webpet-panel canvas{display:block;width:280px;height:320px;background:radial-gradient(circle at 50% 48%,#f5822038,transparent 62%)}.webpet-bubble{position:absolute;z-index:6;right:8px;bottom:366px;max-width:250px;padding:12px 14px;border:1px solid #ffbc7966;border-radius:16px 16px 4px 16px;background:#fffaf4f5;color:#5a2b08;font-size:13px;line-height:1.55;box-shadow:0 12px 30px #51200035;user-select:text}
.webpet-actions{position:absolute;z-index:5;left:50%;bottom:0;display:flex;gap:5px;align-items:center;padding:0;transform:translateX(-50%);background:transparent}.webpet-actions button{height:29px;min-width:42px;padding:0 9px;border-radius:15px;font-size:11px;white-space:nowrap}.webpet-actions [data-pet-record],.webpet-actions [data-pet-chat],.webpet-actions .webpet-close{min-width:29px;width:29px;padding:0;border-radius:50%;font-size:15px}
.webpet-controls{position:absolute;z-index:7;left:14px;right:14px;top:-42px;display:grid;grid-template-columns:1fr 34px;gap:6px;padding:0;background:transparent}.webpet-controls[hidden]{display:none}.webpet-controls input{min-width:0;border:1px solid #ffc99077;border-radius:16px;padding:8px 11px;color:#fff;background:#3f170de8;box-shadow:0 7px 18px #4a1b0044;backdrop-filter:blur(10px);outline:0}.webpet-controls input:focus{border-color:#ffbc79}.webpet-controls input::placeholder{color:#ffd3b6}.webpet-controls button{border-radius:50%}
[data-state=listening] [data-pet-record]{background:#e83e68;animation:pulse 1s infinite}[data-state=thinking] [data-pet-chat]{background:#b78814}[data-state=error] [data-pet-chat]{background:#d73535}[data-state=speaking] [data-pet-record]{background:#168da3}@keyframes pulse{50%{opacity:.48;transform:scale(.88)}}
@media(max-width:640px){[data-web-pet-root]{right:10px;bottom:10px}.webpet-panel{scale:.82;transform-origin:bottom right}}@media(prefers-reduced-motion:reduce){.webpet-panel,.webpet-panel button{animation:none!important;transition:none!important}}
`
